name: Deploy API Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Connect to Server and Build Docker Image
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SERVER_IP }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          GIT_USERNAME: ${{ secrets.SSH_USER }}
          GIT_PASSWORD: ${{ secrets.USER_TOKEN }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST << 'EOF'
            cd /path/to/your/docker/directory &&
            
            # Stop the running container if exists
            docker stop api_go_chatbot_whatsapp_container || true &&
            
            # Remove the old container and image if exist
            docker rm api_go_chatbot_whatsapp_container || true &&
            docker rmi -f api_go_chatbot_whatsapp_image || true &&
            
            # Build a new Docker image
            docker build --no-cache --build-arg GIT_USERNAME=$GIT_USERNAME --build-arg GIT_PASSWORD=$GIT_PASSWORD -t api_go_chatbot_whatsapp_image . &&
            
            # Run the new container
            docker run -d -p 5001:5001 --restart always --name api_go_chatbot_whatsapp_container api_go_chatbot_whatsapp_image
          EOF
